FROM eclipse-temurin:25-jre-alpine
WORKDIR /app
COPY build/libs/chatapps-graph-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8084
ENTRYPOINT ["java", "-XX:+UseSerialGC", "-Xmx256m", "-Xss256k", "-jar", "app.jar"]
