services:
  app:
    build: .
    image: chatapps-graph
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chatapps
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:17-alpine
    container_name: chatapps-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chatapps
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    container_name: chatapps-redis
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    container_name: sb3-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  minio-data: