server:
  port: 8084

spring:
  application:
    name: chatapps-graph
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapps
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: ${redis-timeout}
      jedis:
        pool:
          enabled: true
          min-idle: 1
          max-idle: 10
          max-active: 3
          max-wait: 1000

logging:
  level:
    org.springframework.web: DEBUG
    sql: debug
    org.hibernate.orm.jdbc: debug