server:
  port: 8084

spring:
  application:
    name: chatapps-graph
  datasource:
    url: ${datasource-url}
    username: ${datasource-username}
    password: ${datasource-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${redis-host}
      port: ${redis-port}
      database: ${redis-database}
      username: ${redis-username}
      password: ${redis-password}
      timeout: ${redis-timeout}
      jedis:
        pool:
          enabled: ${redis-pool-enabled}
          min-idle: ${redis-min-idle}
          max-idle: ${redis-max-idle}
          max-active: ${redis-max-active}
          max-wait: ${redis-max-wait}

logging:
  level:
    org.springframework.web: DEBUG
    sql: debug
    org.hibernate.orm.jdbc: debug
